######################## default configuration ####################
baseURL = "http://www.shutupandlisten.co.nz/"
title = "Shut Up & Listen"
theme = "bookworm"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
timeZone = "Pacific/Auckland"

[author]
name = "Nathan"
email = "nathan@outlook.com"

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Image Processing ##############################
[imaging]
quality = 95
resampleFilter = "lanczos"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "css/style_purged.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@400;500;700&display=swap"
async = true
# JS Plugins
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.min.js"
async = true
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/fuse.js/7.0.0/fuse.min.js"
async = true
[[params.plugins.js]]
link = "plugins/search/search.js"
async = true

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

#################### default parameters ################################
[params]
logo = "images/sual-logo.png"
logo_width = "100px"
favicon = "images/favicon.png"

# Meta data
description = "Shut Up & Listen"
author = "Nathan"
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Built by Nathan with content from David"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
weight = 2
url = "categories/gatherings/"
name = "Gatherings"

[[menu.main]]
weight = 2
url = "categories/listen/"
name = "Listen"

[[menu.main]]
weight = 2
url = "members"
name = "Members"


[[menu.main]]
name = "About"
url = "about/"
weight = 3


############################# Footer Menu ########################
[[menu.footer]]
name = "About"
url = "about/"
weight = 1

[[menu.footer]]
name = "Authors"
url = "author/"
weight = 2

# Social Icons
[[params.social]]
icon = "lab la-facebook-f" 
url = "https://github.com/nathan-bell/sual"


